<?php

namespace frontend\controllers;

use frontend\models\RegisterForm;
use common\models\LoginForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

/**
 * Auth Controller handles public registration, login, logout natively
 */
class AuthController extends Controller
{
    /**
     * Apply the blank centered layout for Auth pages globally for this controller
     */
    public $layout = 'main-login';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'register', 'login'],
                'rules' => [
                    [
                        'actions' => ['register', 'login'],
                        'allow' => true,
                        'roles' => ['?'], // Only Guests
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'], // Only Authenticated
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'captcha' => [
                'class' => \yii\captcha\CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'width' => 120,
                'height' => 45,
                'padding' => 1,
            ],
        ];
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        // Reusing default LoginForm generated by Yii2 assuming it's present in common
        // If not, we will need to create it. We assume it exists per yii2-advanced template.
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            // Update last_login_at
            $user = Yii::$app->user->identity;
            $user->last_login_at = time();
            $user->save(false, ['last_login_at']);

            return $this->redirect(['/dashboard/index']);
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionRegister()
    {
        $model = new RegisterForm();

        // Auto format +998 via JS on frontend, but handle edge case internally if needed
        if ($model->load(Yii::$app->request->post())) {

            $user = $model->register();
            if ($user !== false) {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Tabriklaymiz, Muvaffaqiyatli ro\'yxatdan o\'tdingiz!'));

                // Automatically login the newly created user
                if (Yii::$app->getUser()->login($user)) {
                    // Redirect straight to Profile completion Step 1
                    return $this->redirect(['/profile/personal']);
                }
            } else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Kechirasiz, ro\'yxatdan o\'tishda xatolik yuz berdi.'));
            }
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}
