server {
    charset utf-8;
    client_max_body_size 128M;

    listen 80;
    
    server_name localhost;

    root        /app/frontend/web;
    index       index.php;

    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    # Frontend routes
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Backend routes - Accessible via /admin
    location ^~ /admin {
        alias /app/backend/web;
        
        # Rewrite URL to pass through backend's index.php
        try_files $uri $uri/ @backend;

        # Serve static files for backend
        location ~* \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar|eot|svg|ttf|woff|woff2)$ {
            expires max;
            log_not_found off;
            access_log off;
        }

        # PHP-FPM configuration for backend
        location ~ \.php$ {
            fastcgi_pass php:9000;
            include fastcgi_params;
            
            # Extract script path cleanly
            fastcgi_param SCRIPT_FILENAME $request_filename;
            
            # Security setup
            try_files $uri =404;
        }
    }

    location @backend {
        rewrite /admin/(.*)$ /admin/index.php?r=$1 last;
    }

    # PHP-FPM configuration for frontend
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
        try_files $uri =404;
    }

    # Deny access to hidden files
    location ~ /\.(ht|svn|git) {
        deny all;
    }

    # Serve static files for frontend directly
    location ~* \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar|eot|svg|ttf|woff|woff2)$ {
        expires max;
        log_not_found off;
    }
}
